### ISSUE TITLE
Awkward sentence.

### ISSUE THREAD

**Issue by adyavanapalli** [ptkinvent/ptkinvent.github.io#12]
>By combining individual shapes like triangles or lines, you can create complex shapes as simple as point clouds, as complex as dodecahedrons, or any other shape conceivable.

I'm not sure why, but this sentence sounds weird. Maybe do something like this instead?

>By combining individual shapes like triangles or lines, you can create shapes as simple as point clouds or as complex as dodecahedrons.

**Comment by ptkinvent** [comment]
Solved in c0acd66bb0eddbf17b8235643962f9ea5b7f8417.
